name: deploy to lambda

permissions:
  id-token: write
  contents: read

on: 
  push:
    branches:
    - main

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true
          cache-dependency-path: ./backend/go.sum
 
      - name: build functions
        run: make build

      - name: configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::928923391422:role/GitHubActionsLambdaDeploy
          role-duration-seconds: 900
          aws-region: us-east-1
 
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./backend/ && sls deploy --verbose"
          entrypoint: /bin/sh
        
         
      
