name: deploy to lambda

permissions:
  id-token: write
  contents: read

on: 
  push:
    branches:
    - master

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true
          cache-dependency-path: ./backend/go.sum
          
      - name: Build
        run: go build -v ./...
        
#      - name: Test
#        run: go test -v ./...
 
      - name: Zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./backend/
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::928923391422:role/GitHubActionsLambdaDeploy
          role-duration-seconds: 900
          aws-region: us-east-1
 
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        
         
      
