name: deploy to lambda

permissions:
  id-token: write
  contents: read

on: 
  push:
    branches:
    - main

jobs:
  check_backend_changes:
    name: check changes to backend
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changed.outputs.backend }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changed
        with:
          filters: |
              backend:
                - 'backend/**'
  deploy_source:
    name: build backend and deploy
    runs-on: ubuntu-latest
#     needs: [ check_backend_changes ]
#     if: needs.check_backend_changes.outputs.changed == 'true'
    defaults:
      run:
        working-directory: ./backend/
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      # - name: get changed files in backend
      #   id: changed-files-backend
      #   uses: tj-actions/changed-files@v35
      #   with:
      #     files: |
      #         backend/**

      - name: set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true
          cache-dependency-path: ./backend/go.sum
 
      - name: generate secrets
        run: |
            echo "$SECRETS" >> .secrets.yml
        shell: bash
        env:
          SECRETS: ${{secrets.secrets}}

      - name: configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::928923391422:role/GitHubActionsLambdaDeploy
          role-duration-seconds: 900
          aws-region: us-east-1
          
      - name: configure NPM for serverless
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: install backend packages
        run: npm ci && npm -i serverless
 
#       - name: serverless deploy
#         uses: serverless/github-action@v3.1
#         with:
#           args: -c "cd ./backend/ && make"
#           entrypoint: /bin/bash

      - name: build and deploy
        run: make
        
      - name: remove secrets
        run: rm .secrets.yml
        shell: bash
      
